<template>
  <div class="container">
    <article class="content">
      <h1>Privacy Policy</h1>
      <p>Our Privacy Policy (&ldquo;Privacy&rdquo;) is designed to explain what information we collect from you as a user, how your information is collected, and how we may use it on hiTarget. As you will see in the Privacy Policy, we only use the collected information to improve hiTarget for our users.</p>
      <h2>INTERPRETATION</h2>
      <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
      <h2>DEFINITIONS</h2>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
      <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
      <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to hiTarget.</li>
      <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
      <li><strong>Country</strong> refers to: Ontario, Canada</li>
      <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
      <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
      <li><strong>Service</strong> refers to the Website.</li>
      <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
      <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
      <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
      <li><strong>Website</strong> refers to hiTarget, accessible from<a href="https://hitarget.me" target="_blank" rel="noopener">https://hitarget.me</a></li>
      <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>
      <h3>INFORMATION PRIVACY</h3>
      <p>hiTarget maintains reasonable security measures to protect your information from loss, destruction, misuse, unauthorized access or disclosure. This helps to ensure that your data is safe, secure, and only available to you and those you provide with authorized access. We do not and will not sell your personal information to third parties. Unfortunately, no data transmission over the Internet or information storage technology can be guaranteed to be 100% secure due to the nature of the distributed network that is the Internet. hiTarget is not liable for any loss or damage resulting from data gathered by unauthorized access to hiTarget from hacking, social engineering, or otherwise circumventing our security measures. We do, however, take appropriate measures to try to prevent such events from occurring.</p>
      <h3>YOUR PERSONAL INFORMATION</h3>
      <p>We collect the email addresses of those who communicate with us via email. When you use hiTarget, we track anonymous data for analytical purposes. We'll also store any information you voluntarily submit (for example, filling out a survey) for the duration of the research project or as long as it makes sense. When you sign up for hiTarget, we ask for your email address and your name. This allows us to send you invoices, updates, or contact you concerning your account. We&rsquo;ll never give nor sell your personal information to third parties.</p>
      <h3>INFORMATION FROM THIRD-PARTY SOCIAL MEDIA SERVICES</h3>
      <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
      <ul>
      <li>Google</li>
      <li>Facebook</li>
      <li>Twitter</li>
      </ul>
      <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
      <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
      <h3>WE USE YOUR INFORMATION</h3>
      <ul>
      <li>To create your account;</li>
      <li>To bill you for services;</li>
      <li>To provide customer support;</li>
      <li>To transfer your information in the case of a sale, merger, consolidation, or acquisition;</li>
      <li>To better understand your needs and interests;</li>
      <li>To send newsletters, message or notification via website and our application.</li>
      <li>To personalize your experience;</li>
      <li>To improve hiTarget.</li>
      </ul>
      <h3>HOW WE SHARE AND DISCLOSURE YOUR PERSONAL INFORMATION</h3>
      <p>While we never share your personal information with non-affiliated companies, we may share your personal information in the following ways:</p>
      <p>We may share information with service providers who provide necessary services to hiTarget (our Suprocessors) &ndash; for instance to send out newsletters or to process payments;</p>
      <p>When we have your permission to share your information;</p>
      <p>When we are required by law, or legal process to disclose that information &ndash; such as a valid court order or a valid subpoena. When we believe in good faith that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or respond to a valid governmental request.</p>
      <p>To enforce our terms or to protect our operations or users;</p>
      <p>If a transfer of your information is required under the terms of a reorganization, merger, or sale of the company;</p>
      <h3>COOKIES</h3>
      <p>When you use hiTarget we and our Subprocessors may use &ldquo;cookies&rdquo;, &ldquo;web beacons&rdquo;, and similar devices to track your activities. These small pieces of information are stored on your hard drive, not on hiTarget services. We use cookies to help you navigate hiTarget as easily as possible, and to remember information about your current session. We do not use this technology to spy on you or otherwise invade your privacy. You can disable cookies and tracking technologies through your web browser, however doing so may make hiTarget less usable.</p>
      <h3>ANALYTICS</h3>
      <p>We use Google Analytics to measure and evaluate access to and traffic on hiTarget. Google operates independently from us and has its own privacy policy, which we strongly suggest you review.</p>
      <h3>SECURITY AND STORAGE</h3>
      <p>hiTarget has industry standard security measures in place to protect the loss, misuse, and alteration of the information under our control. While there is no such thing as "perfect security" on the Internet, we will take all reasonable steps to ensure the safety of your information.</p>
      <h3>CORRECTING AND UPDATING INFORMATION</h3>
      <p>If you are our customer and would like to access or delete information that you provided, you may contact us inside hiTarget. We may decline to process unreasonable requests or requests that are not otherwise required by local law. We retain your information and data that we process on your behalf as long as your account is active, as needed to provide our Services, and as necessary to comply with our legal obligations and to resolve disputes.</p>
      <h3>DELETED DATA</h3>
      <p>When you remove your account, we delete all data associated with your account from our production database. We do keep backups, designed for catastrophic system recovery, for 30 days. The backups are purged on a rolling 30 day cycle. When an account is deleted, none of your personal data will remain on our servers past 30 days. Anything you delete from your account while it&rsquo;s active will also be purged from the backups on day 30. Deactivated users will no longer have access to your account, but their name, email addresses, and time entries will remain in your account for historical reporting purposes.</p>
      <h3>UPDATES TO THIS PRIVACY</h3>
      <p>hiTarget reserves the right to update this policy at any time without prior notice, so please review it frequently.</p>
      <h3>QUESTIONS</h3>
      <p>If you have any questions or concerns about the Privacy Policy,&nbsp; please contact us using Support link inside hiTarget.</p>
      <h4>LAST UPDATED: March 4, 2021</h4>
    </article>
  </div>
</template>
